/**
 * Neighborhood insights imported from snohomish-landing.
 * Source: snohomish-landing/data/neighborhood_page_index.json + HTML pages
 * Extracted: 2026-07-18
 */

export interface SnohoNeighborhood {
  slug: string;
  name: string;
  parentSlug: string;
  parentName: string;
  route: string;
  bestFit: string;
  tradeoff: string;
  localTexture: string;
  compareNext: string;
  medianPrice: number;
  homesSold: number;
  medianDom: number;
  monthsSupply: number;
  newListings: number;
}

export const snohoNeighborhoods: SnohoNeighborhood[] = [
  {
    slug: 'blackmans-lake',
    name: "Blackmans Lake",
    parentSlug: 'snohomish',
    parentName: "Snohomish",
    route: '/blackmans-lake-in-snohomish-wa',
    bestFit: "Buyers who want Snohomish identity with a more conventional neighborhood pattern.",
    tradeoff: "It can feel less distinctive than the historic core.",
    localTexture: "Blackmans Lake often keeps Snohomish viable for buyers who want the city but not necessarily its oldest housing stock.",
    compareNext: "Downtown for charm, or Three Lakes / Cathcart for more space.",
    medianPrice: 742500,
    homesSold: 17,
    medianDom: 26.0,
    monthsSupply: 2.2,
    newListings: 23,
  },
  {
    slug: 'fobes-hill-dutch-hill',
    name: "Fobes Hill / Dutch Hill",
    parentSlug: 'snohomish',
    parentName: "Snohomish",
    route: '/fobes-hill-dutch-hill-in-snohomish-wa',
    bestFit: "Buyers prioritizing privacy and residential calm.",
    tradeoff: "It may feel less connected to the small-town center than downtown or Blackmans Lake.",
    localTexture: "This is one of the most common Snohomish pockets for buyers who want the city but not the busiest parts of it.",
    compareNext: "Three Lakes / Cathcart for more land, or Blackmans Lake for easier everyday access.",
    medianPrice: 742500,
    homesSold: 17,
    medianDom: 26.0,
    monthsSupply: 2.2,
    newListings: 23,
  },
  {
    slug: 'historic-downtown-snohomish',
    name: "Historic Downtown Snohomish",
    parentSlug: 'snohomish',
    parentName: "Snohomish",
    route: '/historic-downtown-snohomish-in-snohomish-wa',
    bestFit: "Buyers who care about place, charm, and older homes with personality.",
    tradeoff: "It is not the easiest fit for buyers who want newer-home efficiency or purely suburban convenience.",
    localTexture: "Historic downtown is usually what people picture when they think they want Snohomish.",
    compareNext: "Blackmans Lake for easier daily living, or Fobes Hill for more privacy.",
    medianPrice: 742500,
    homesSold: 17,
    medianDom: 26.0,
    monthsSupply: 2.2,
    newListings: 23,
  },
  {
    slug: 'three-lakes-cathcart',
    name: "Three Lakes / Cathcart",
    parentSlug: 'snohomish',
    parentName: "Snohomish",
    route: '/three-lakes-cathcart-in-snohomish-wa',
    bestFit: "Buyers who want room, distance, and a slower rhythm.",
    tradeoff: "You typically give up some convenience to get it.",
    localTexture: "Three Lakes / Cathcart is where Snohomish starts to overlap with acreage-driven decision-making.",
    compareNext: "Fobes Hill for a slightly closer-in version of privacy, or Arlington if you want north-county room instead.",
    medianPrice: 742500,
    homesSold: 17,
    medianDom: 26.0,
    monthsSupply: 2.2,
    newListings: 23,
  },
  {
    slug: 'north-everett',
    name: "North Everett",
    parentSlug: 'everett',
    parentName: "Everett",
    route: '/north-everett-in-everett-wa',
    bestFit: "Buyers who want Everett to feel like a city instead of just a value play.",
    tradeoff: "It is not the easiest fit for buyers who want a newer or more suburban-feeling environment.",
    localTexture: "North Everett often determines whether a buyer is actually an Everett person or just Everett-curious.",
    compareNext: "Silver Lake for suburban comfort, or South Everett for a more functional commuter setup.",
    medianPrice: 587500,
    homesSold: 90,
    medianDom: 7.0,
    monthsSupply: 1.8,
    newListings: 124,
  },
  {
    slug: 'northwest-everett',
    name: "Northwest Everett",
    parentSlug: 'everett',
    parentName: "Everett",
    route: '/northwest-everett-in-everett-wa',
    bestFit: "Buyers who want Everett character with a little less edge.",
    tradeoff: "It may not deliver the same purely practical commute benefits as South Everett.",
    localTexture: "This is a useful middle ground between classic city Everett and more suburban pockets.",
    compareNext: "North Everett for stronger identity, or Silver Lake for a newer-feeling suburban rhythm.",
    medianPrice: 587500,
    homesSold: 90,
    medianDom: 7.0,
    monthsSupply: 1.8,
    newListings: 124,
  },
  {
    slug: 'silver-lake-everett',
    name: "Silver Lake",
    parentSlug: 'everett',
    parentName: "Everett",
    route: '/silver-lake-everett-in-everett-wa',
    bestFit: "Families or suburban buyers who still want Everett access.",
    tradeoff: "It gives up some of Everett\'s city identity in exchange for ease and familiarity.",
    localTexture: "Silver Lake is often the neighborhood that keeps suburban buyers in the Everett conversation.",
    compareNext: "North Everett for character, or Mukilteo if you want a more polished residential feel.",
    medianPrice: 587500,
    homesSold: 90,
    medianDom: 7.0,
    monthsSupply: 1.8,
    newListings: 124,
  },
  {
    slug: 'south-everett',
    name: "South Everett",
    parentSlug: 'everett',
    parentName: "Everett",
    route: '/south-everett-in-everett-wa',
    bestFit: "Commute-first or job-access buyers.",
    tradeoff: "It feels more functional than lifestyle-driven.",
    localTexture: "South Everett usually wins when the question is about usefulness, not romance.",
    compareNext: "Mukilteo if you want more polish, or North Everett if you want more identity.",
    medianPrice: 587500,
    homesSold: 90,
    medianDom: 7.0,
    monthsSupply: 1.8,
    newListings: 124,
  },
  {
    slug: 'central-marysville',
    name: "Central Marysville",
    parentSlug: 'marysville',
    parentName: "Marysville",
    route: '/central-marysville-in-marysville-wa',
    bestFit: "Value-first buyers who want the city to function well.",
    tradeoff: "It does not offer the most elevated or distinctive neighborhood identity.",
    localTexture: "Central Marysville usually wins when the move is about practical ownership more than brand-name lifestyle.",
    compareNext: "Lakewood for a more residential feel, or Everett for stronger city identity.",
    medianPrice: 649990,
    homesSold: 83,
    medianDom: 9.0,
    monthsSupply: 2.7,
    newListings: 132,
  },
  {
    slug: 'getchell-whiskey-ridge',
    name: "Getchell / Whiskey Ridge",
    parentSlug: 'marysville',
    parentName: "Marysville",
    route: '/getchell-whiskey-ridge-in-marysville-wa',
    bestFit: "Buyers who want Marysville to feel more finished and residential.",
    tradeoff: "It generally moves away from Marysville\'s strongest value proposition.",
    localTexture: "This is often the pocket that changes how skeptical buyers feel about Marysville.",
    compareNext: "Lake Stevens for another suburban-family option, or central Marysville if budget pressure matters more.",
    medianPrice: 649990,
    homesSold: 83,
    medianDom: 9.0,
    monthsSupply: 2.7,
    newListings: 132,
  },
  {
    slug: 'lakewood-marysville',
    name: "Lakewood",
    parentSlug: 'marysville',
    parentName: "Marysville",
    route: '/lakewood-marysville-in-marysville-wa',
    bestFit: "Buyers who want Marysville with a gentler neighborhood pattern.",
    tradeoff: "It may not be as directly convenient as central Marysville.",
    localTexture: "Lakewood often appeals to buyers who like Marysville\'s numbers but not always its busiest streets.",
    compareNext: "Sunnyside for a middle ground, or Lake Stevens for a more curated suburban feel.",
    medianPrice: 649990,
    homesSold: 83,
    medianDom: 9.0,
    monthsSupply: 2.7,
    newListings: 132,
  },
  {
    slug: 'sunnyside-marysville',
    name: "Sunnyside",
    parentSlug: 'marysville',
    parentName: "Marysville",
    route: '/sunnyside-marysville-in-marysville-wa',
    bestFit: "Buyers seeking balance rather than a hard lean toward either convenience or new construction.",
    tradeoff: "It may not feel as obviously strategic as central Marysville or as polished as Whiskey Ridge.",
    localTexture: "Sunnyside is usually where Marysville feels the most broadly useful without being too one-note.",
    compareNext: "Central Marysville for pure practicality, or Getchell / Whiskey Ridge for a more elevated suburban feel.",
    medianPrice: 649990,
    homesSold: 83,
    medianDom: 9.0,
    monthsSupply: 2.7,
    newListings: 132,
  },
  {
    slug: 'downtown-arlington',
    name: "Downtown Arlington",
    parentSlug: 'arlington',
    parentName: "Arlington",
    route: '/downtown-arlington-in-arlington-wa',
    bestFit: "Character-first buyers who want a recognizable center instead of a purely subdivision-driven search.",
    tradeoff: "It offers less land and less suburban polish than farther-out Arlington pockets.",
    localTexture: "This is usually the first neighborhood buyers tour when they want Arlington to feel distinct instead of generic.",
    compareNext: "Smokey Point if daily practicality matters more, and East Arlington if acreage matters more.",
    medianPrice: 612000,
    homesSold: 21,
    medianDom: 17.0,
    monthsSupply: 1.9,
    newListings: 36,
  },
  {
    slug: 'east-arlington',
    name: "East Arlington / Rural Edge",
    parentSlug: 'arlington',
    parentName: "Arlington",
    route: '/east-arlington-in-arlington-wa',
    bestFit: "Space-first buyers who are comfortable trading convenience for breathing room.",
    tradeoff: "Daily driving is usually the price of entry.",
    localTexture: "This is the pocket that most clearly delivers on Arlington\'s \'more room and slower pace\' promise.",
    compareNext: "Gleneagle if you want more polish, or downtown Arlington if you want more of a town-center feel.",
    medianPrice: 612000,
    homesSold: 21,
    medianDom: 17.0,
    monthsSupply: 1.9,
    newListings: 36,
  },
  {
    slug: 'gleneagle',
    name: "Gleneagle",
    parentSlug: 'arlington',
    parentName: "Arlington",
    route: '/gleneagle-in-arlington-wa',
    bestFit: "Buyers who value predictability, neighborhood consistency, and a more polished residential pattern.",
    tradeoff: "It gives up some of the elbow room and outdoor-edge feel that pull buyers north in the first place.",
    localTexture: "Gleneagle is often where Arlington starts to feel more suburban and less edge-of-county.",
    compareNext: "Smokey Point if convenience matters more, or East Arlington if land matters more.",
    medianPrice: 612000,
    homesSold: 21,
    medianDom: 17.0,
    monthsSupply: 1.9,
    newListings: 36,
  },
  {
    slug: 'smokey-point',
    name: "Smokey Point",
    parentSlug: 'arlington',
    parentName: "Arlington",
    route: '/smokey-point-in-arlington-wa',
    bestFit: "Households prioritizing daily convenience and a less complicated routine.",
    tradeoff: "It feels more utilitarian and less town-centered than downtown Arlington.",
    localTexture: "If the question is \'what part of Arlington makes ordinary life easiest?\' this is usually the answer.",
    compareNext: "Downtown Arlington for identity, or Gleneagle for a more finished subdivision feel.",
    medianPrice: 612000,
    homesSold: 21,
    medianDom: 17.0,
    monthsSupply: 1.9,
    newListings: 36,
  },
  {
    slug: 'frontier-village',
    name: "Frontier Village",
    parentSlug: 'lake-stevens',
    parentName: "Lake Stevens",
    route: '/frontier-village-in-lake-stevens-wa',
    bestFit: "Convenience-first buyers.",
    tradeoff: "It can feel busier and less quiet than other parts of the city.",
    localTexture: "When buyers ask which part of Lake Stevens feels most usable day to day, Frontier Village is usually near the top.",
    compareNext: "West Lake Stevens for a more suburban feel, or North Lake Stevens for a quieter setup.",
    medianPrice: 748116,
    homesSold: 50,
    medianDom: 14.0,
    monthsSupply: 2.3,
    newListings: 67,
  },
  {
    slug: 'lundeen',
    name: "Lundeen",
    parentSlug: 'lake-stevens',
    parentName: "Lake Stevens",
    route: '/lundeen-in-lake-stevens-wa',
    bestFit: "Lake-lifestyle buyers who want more identity in the search.",
    tradeoff: "It may be less purely practical than the city\'s convenience-oriented pockets.",
    localTexture: "Lundeen is where the Lake Stevens search usually becomes more lifestyle-driven.",
    compareNext: "West Lake Stevens for all-around suburbia, or Snohomish if you want a different kind of character.",
    medianPrice: 748116,
    homesSold: 50,
    medianDom: 14.0,
    monthsSupply: 2.3,
    newListings: 67,
  },
  {
    slug: 'north-lake-stevens',
    name: "North Lake Stevens",
    parentSlug: 'lake-stevens',
    parentName: "Lake Stevens",
    route: '/north-lake-stevens-in-lake-stevens-wa',
    bestFit: "Buyers who prioritize a calmer residential pattern.",
    tradeoff: "You usually trade some immediacy of access for that quieter feel.",
    localTexture: "North Lake Stevens often keeps the city on the list for buyers who dislike busier retail-adjacent pockets.",
    compareNext: "Frontier Village for convenience, or Arlington if you want even more space.",
    medianPrice: 748116,
    homesSold: 50,
    medianDom: 14.0,
    monthsSupply: 2.3,
    newListings: 67,
  },
  {
    slug: 'west-lake-stevens',
    name: "West Lake Stevens",
    parentSlug: 'lake-stevens',
    parentName: "Lake Stevens",
    route: '/west-lake-stevens-in-lake-stevens-wa',
    bestFit: "Buyers who want a straightforward suburban setup.",
    tradeoff: "It may feel less distinct than the lake-adjacent pockets.",
    localTexture: "West Lake Stevens tends to be the safest starting point for relocation families.",
    compareNext: "Lundeen if lake identity matters more, or Frontier Village if errands matter more.",
    medianPrice: 748116,
    homesSold: 50,
    medianDom: 14.0,
    monthsSupply: 2.3,
    newListings: 67,
  },
  {
    slug: 'canyon-park',
    name: "Canyon Park",
    parentSlug: 'bothell',
    parentName: "Bothell",
    route: '/canyon-park-in-bothell-wa',
    bestFit: "Buyers who want Bothell with the clearest job-access logic.",
    tradeoff: "It feels more strategic and growth-oriented than cozy or small-scale.",
    localTexture: "Bothell treats Canyon Park as a Regional Growth Center and major employment district.",
    compareNext: "Downtown for more identity, or North Creek for more park-and-trail context.",
    medianPrice: 1099950,
    homesSold: 53,
    medianDom: 13.0,
    monthsSupply: 2.9,
    newListings: 78,
  },
  {
    slug: 'downtown-bothell',
    name: "Downtown Bothell",
    parentSlug: 'bothell',
    parentName: "Bothell",
    route: '/downtown-bothell-in-bothell-wa',
    bestFit: "Buyers who want a walkable-feeling center and a more urbanized version of Bothell.",
    tradeoff: "It is less suburban and less tucked away than many buyers expect when they first search Bothell.",
    localTexture: "Official city planning centers downtown as one of Bothell\'s key gathering and growth areas.",
    compareNext: "Canyon Park for job access, or Norway Hill for a more residential setting.",
    medianPrice: 1099950,
    homesSold: 53,
    medianDom: 13.0,
    monthsSupply: 2.9,
    newListings: 78,
  },
  {
    slug: 'north-creek',
    name: "North Creek",
    parentSlug: 'bothell',
    parentName: "Bothell",
    route: '/north-creek-in-bothell-wa',
    bestFit: "Buyers who want Bothell access with strong park and trail context.",
    tradeoff: "It may feel more distributed and less centered than downtown Bothell.",
    localTexture: "The city maintains North Creek sports fields, trail connections, and North Creek Forest in this part of Bothell.",
    compareNext: "Canyon Park for more employment-hub energy, or Norway Hill for a more traditional residential feel.",
    medianPrice: 1099950,
    homesSold: 53,
    medianDom: 13.0,
    monthsSupply: 2.9,
    newListings: 78,
  },
  {
    slug: 'norway-hill',
    name: "Norway Hill",
    parentSlug: 'bothell',
    parentName: "Bothell",
    route: '/norway-hill-in-bothell-wa',
    bestFit: "Buyers who want Bothell without centering office parks or downtown energy.",
    tradeoff: "It may not offer the same direct utility as Canyon Park or downtown.",
    localTexture: "East Norway Hill Park gives this part of Bothell a clearer forested, neighborhood-park identity.",
    compareNext: "Downtown for more city energy, or North Creek for more active recreation context.",
    medianPrice: 1099950,
    homesSold: 53,
    medianDom: 13.0,
    monthsSupply: 2.9,
    newListings: 78,
  },
  {
    slug: 'alderwood',
    name: "Alderwood",
    parentSlug: 'lynnwood',
    parentName: "Lynnwood",
    route: '/alderwood-in-lynnwood-wa',
    bestFit: "Commuters and utility-first buyers.",
    tradeoff: "It can feel more functional than distinctive.",
    localTexture: "Alderwood is where many buyers decide whether Lynnwood\'s practicality is a feature or a drawback.",
    compareNext: "Meadowdale for more neighborhood feel, or Mukilteo for more polish.",
    medianPrice: 820000,
    homesSold: 27,
    medianDom: 6.0,
    monthsSupply: 2.2,
    newListings: 45,
  },
  {
    slug: 'east-lynnwood',
    name: "East Lynnwood",
    parentSlug: 'lynnwood',
    parentName: "Lynnwood",
    route: '/east-lynnwood-in-lynnwood-wa',
    bestFit: "405-oriented commuters and cross-shoppers between Lynnwood and Bothell.",
    tradeoff: "It is less centered on Lynnwood\'s most obvious convenience zones.",
    localTexture: "East Lynnwood is usually the neighborhood that keeps Lynnwood in the running for buyers with more eastward commute patterns.",
    compareNext: "Bothell if you want more Eastside adjacency, or Meadowdale if you want a more residential feel.",
    medianPrice: 820000,
    homesSold: 27,
    medianDom: 6.0,
    monthsSupply: 2.2,
    newListings: 45,
  },
  {
    slug: 'meadowdale',
    name: "Meadowdale",
    parentSlug: 'lynnwood',
    parentName: "Lynnwood",
    route: '/meadowdale-in-lynnwood-wa',
    bestFit: "Buyers who want Lynnwood with a calmer neighborhood identity.",
    tradeoff: "It may not feel as directly convenient as Alderwood.",
    localTexture: "Meadowdale often keeps Lynnwood viable for buyers who initially think it feels too utilitarian.",
    compareNext: "Alderwood for access, or Snohomish for even more place-driven identity.",
    medianPrice: 820000,
    homesSold: 27,
    medianDom: 6.0,
    monthsSupply: 2.2,
    newListings: 45,
  },
  {
    slug: 'north-lynnwood',
    name: "North Lynnwood",
    parentSlug: 'lynnwood',
    parentName: "Lynnwood",
    route: '/north-lynnwood-in-lynnwood-wa',
    bestFit: "Buyers looking for the middle ground in Lynnwood.",
    tradeoff: "It may not lead the city on either pure convenience or pure charm.",
    localTexture: "North Lynnwood is often where the city starts to feel more livable and less purely transactional.",
    compareNext: "Alderwood for stronger utility, or Meadowdale for stronger neighborhood feel.",
    medianPrice: 820000,
    homesSold: 27,
    medianDom: 6.0,
    monthsSupply: 2.2,
    newListings: 45,
  },
  {
    slug: 'central-mukilteo',
    name: "Central Mukilteo",
    parentSlug: 'mukilteo',
    parentName: "Mukilteo",
    route: '/central-mukilteo-in-mukilteo-wa',
    bestFit: "Buyers looking for a middle ground in Mukilteo.",
    tradeoff: "It may not deliver the strongest version of either practicality or prestige.",
    localTexture: "Central Mukilteo is often the part of town that keeps budget-conscious buyers from dropping the city too early.",
    compareNext: "Harbour Pointe for more polish, or the Paine Field side for more commute logic.",
    medianPrice: 941500,
    homesSold: 26,
    medianDom: 5.0,
    monthsSupply: 2.0,
    newListings: 43,
  },
  {
    slug: 'harbour-pointe',
    name: "Harbour Pointe",
    parentSlug: 'mukilteo',
    parentName: "Mukilteo",
    route: '/harbour-pointe-in-mukilteo-wa',
    bestFit: "Buyers prioritizing polish and residential presentation.",
    tradeoff: "It generally comes with less of the raw waterfront identity than Old Town.",
    localTexture: "Harbour Pointe is often the strongest fit for buyers cross-shopping Mukilteo against upscale south-county alternatives.",
    compareNext: "Old Town for lifestyle, or central Mukilteo for a more balanced price-and-location conversation.",
    medianPrice: 941500,
    homesSold: 26,
    medianDom: 5.0,
    monthsSupply: 2.0,
    newListings: 43,
  },
  {
    slug: 'old-town-mukilteo',
    name: "Old Town Mukilteo",
    parentSlug: 'mukilteo',
    parentName: "Mukilteo",
    route: '/old-town-mukilteo-in-mukilteo-wa',
    bestFit: "View-driven and place-driven buyers.",
    tradeoff: "It is not the easiest answer for buyers who want pure practicality.",
    localTexture: "Old Town is where Mukilteo stops feeling like a suburb and starts feeling like a destination.",
    compareNext: "Harbour Pointe for polish, or the Paine Field side for functionality.",
    medianPrice: 941500,
    homesSold: 26,
    medianDom: 5.0,
    monthsSupply: 2.0,
    newListings: 43,
  },
  {
    slug: 'paine-field-edge',
    name: "Paine Field Edge",
    parentSlug: 'mukilteo',
    parentName: "Mukilteo",
    route: '/paine-field-edge-in-mukilteo-wa',
    bestFit: "Job-access and function-first households.",
    tradeoff: "It lacks the strongest version of Mukilteo\'s signature coastal identity.",
    localTexture: "This is where Mukilteo starts to make sense for buyers who normally would have dismissed it as too lifestyle-heavy.",
    compareNext: "Everett for more value, or Old Town for more character.",
    medianPrice: 941500,
    homesSold: 26,
    medianDom: 5.0,
    monthsSupply: 2.0,
    newListings: 43,
  },
  {
    slug: 'aspen',
    name: "Aspen",
    parentSlug: 'mill-creek',
    parentName: "Mill Creek",
    route: '/aspen-in-mill-creek-wa',
    bestFit: "Buyers who want to pressure-test Aspen against the other best-known parts of Mill Creek instead of stopping at the city-wide guide.",
    tradeoff: "This page is a neighborhood-level starting point, so pair Aspen with the full Mill Creek guide and the Snohomish County report before making a block-by-block decision.",
    localTexture: "Mill Creek is currently around $742K, 14 days on market, and 47 active listings, so Aspen should be read inside that broader city market.",
    compareNext: "Compare Aspen with Cypress and Magnolia to see which side of Mill Creek fits better.",
    medianPrice: 741750,
    homesSold: 16,
    medianDom: 14.0,
    monthsSupply: 2.9,
    newListings: 30,
  },
  {
    slug: 'cypress',
    name: "Cypress",
    parentSlug: 'mill-creek',
    parentName: "Mill Creek",
    route: '/cypress-in-mill-creek-wa',
    bestFit: "Buyers who want to pressure-test Cypress against the other best-known parts of Mill Creek instead of stopping at the city-wide guide.",
    tradeoff: "This page is a neighborhood-level starting point, so pair Cypress with the full Mill Creek guide and the Snohomish County report before making a block-by-block decision.",
    localTexture: "Mill Creek is currently around $742K, 14 days on market, and 47 active listings, so Cypress should be read inside that broader city market.",
    compareNext: "Compare Cypress with Aspen and Magnolia to see which side of Mill Creek fits better.",
    medianPrice: 741750,
    homesSold: 16,
    medianDom: 14.0,
    monthsSupply: 2.9,
    newListings: 30,
  },
  {
    slug: 'juniper',
    name: "Juniper",
    parentSlug: 'mill-creek',
    parentName: "Mill Creek",
    route: '/juniper-in-mill-creek-wa',
    bestFit: "Buyers who want to pressure-test Juniper against the other best-known parts of Mill Creek instead of stopping at the city-wide guide.",
    tradeoff: "This page is a neighborhood-level starting point, so pair Juniper with the full Mill Creek guide and the Snohomish County report before making a block-by-block decision.",
    localTexture: "Mill Creek is currently around $742K, 14 days on market, and 47 active listings, so Juniper should be read inside that broader city market.",
    compareNext: "Compare Juniper with Cypress and Aspen to see which side of Mill Creek fits better.",
    medianPrice: 741750,
    homesSold: 16,
    medianDom: 14.0,
    monthsSupply: 2.9,
    newListings: 30,
  },
  {
    slug: 'magnolia',
    name: "Magnolia",
    parentSlug: 'mill-creek',
    parentName: "Mill Creek",
    route: '/magnolia-in-mill-creek-wa',
    bestFit: "Buyers who want to pressure-test Magnolia against the other best-known parts of Mill Creek instead of stopping at the city-wide guide.",
    tradeoff: "This page is a neighborhood-level starting point, so pair Magnolia with the full Mill Creek guide and the Snohomish County report before making a block-by-block decision.",
    localTexture: "Mill Creek is currently around $742K, 14 days on market, and 47 active listings, so Magnolia should be read inside that broader city market.",
    compareNext: "Compare Magnolia with Cypress and Aspen to see which side of Mill Creek fits better.",
    medianPrice: 741750,
    homesSold: 16,
    medianDom: 14.0,
    monthsSupply: 2.9,
    newListings: 30,
  },
  {
    slug: 'college-way-corridor',
    name: "College Way Corridor",
    parentSlug: 'mount-vernon',
    parentName: "Mount Vernon",
    route: '/college-way-corridor-in-mount-vernon-wa',
    bestFit: "Convenience-first buyers who still want Skagit County.",
    tradeoff: "It can feel more corridor-driven than neighborhood-rich.",
    localTexture: "If the move is about usable daily life, the College Way corridor is usually near the top of the shortlist.",
    compareNext: "Downtown for more identity, or West Mount Vernon for a softer residential feel.",
    medianPrice: 625000,
    homesSold: 29,
    medianDom: 11.0,
    monthsSupply: 3.2,
    newListings: 64,
  },
  {
    slug: 'downtown-mount-vernon',
    name: "Downtown Mount Vernon",
    parentSlug: 'mount-vernon',
    parentName: "Mount Vernon",
    route: '/downtown-mount-vernon-in-mount-vernon-wa',
    bestFit: "City-center and identity-driven buyers.",
    tradeoff: "It is less purely functional than the most convenience-oriented parts of town.",
    localTexture: "Downtown is where many buyers decide whether Mount Vernon feels too far out or exactly right.",
    compareNext: "College Way for utility, or Hilltop for a more residential version of Mount Vernon.",
    medianPrice: 625000,
    homesSold: 29,
    medianDom: 11.0,
    monthsSupply: 3.2,
    newListings: 64,
  },
  {
    slug: 'hilltop-mount-vernon',
    name: "Hilltop",
    parentSlug: 'mount-vernon',
    parentName: "Mount Vernon",
    route: '/hilltop-mount-vernon-in-mount-vernon-wa',
    bestFit: "Buyers who want a residential identity first.",
    tradeoff: "It may not be as immediately convenient as the College Way side.",
    localTexture: "Hilltop often makes Mount Vernon feel more like a neighborhood search and less like a generic small-city search.",
    compareNext: "Downtown for city-center feel, or West Mount Vernon for a quieter balance.",
    medianPrice: 625000,
    homesSold: 29,
    medianDom: 11.0,
    monthsSupply: 3.2,
    newListings: 64,
  },
  {
    slug: 'west-mount-vernon',
    name: "West Mount Vernon",
    parentSlug: 'mount-vernon',
    parentName: "Mount Vernon",
    route: '/west-mount-vernon-in-mount-vernon-wa',
    bestFit: "Buyers who want calm without losing the city entirely.",
    tradeoff: "It may not have the strongest identity or the strongest utility compared with Mount Vernon\'s other pockets.",
    localTexture: "West Mount Vernon is often the compromise neighborhood that helps the city stay on the list.",
    compareNext: "Hilltop for more established feel, or College Way for more convenience.",
    medianPrice: 625000,
    homesSold: 29,
    medianDom: 11.0,
    monthsSupply: 3.2,
    newListings: 64,
  },
  {
    slug: 'downtown-bowl-edmonds',
    name: "Downtown / Bowl",
    parentSlug: 'edmonds',
    parentName: "Edmonds",
    route: '/downtown-bowl-edmonds-in-edmonds-wa',
    bestFit: "Lifestyle buyers who want charm, water views, and a real destination center.",
    tradeoff: "It is less value-driven and less purely practical than inland Edmonds options.",
    localTexture: "Downtown Edmonds is often where buyers decide whether Edmonds feels special enough to justify its pricing.",
    compareNext: "Mukilteo for another waterfront feel, or Meadowdale for a quieter residential pattern.",
    medianPrice: 986500,
    homesSold: 52,
    medianDom: 7.0,
    monthsSupply: 2.3,
    newListings: 102,
  },
  {
    slug: 'meadowdale-edmonds',
    name: "Meadowdale",
    parentSlug: 'edmonds',
    parentName: "Edmonds",
    route: '/meadowdale-edmonds-in-edmonds-wa',
    bestFit: "Buyers prioritizing a calmer, more residential version of Edmonds.",
    tradeoff: "It is less tied to the ferry, Bowl, and downtown identity most people associate with Edmonds.",
    localTexture: "Meadowdale is usually where Edmonds starts to feel more like a residential shoreline community than a destination town.",
    compareNext: "Yost / Maplewood for more central park access, or Downtown Edmonds for stronger place identity.",
    medianPrice: 986500,
    homesSold: 52,
    medianDom: 7.0,
    monthsSupply: 2.3,
    newListings: 102,
  },
  {
    slug: 'westgate-five-corners-edmonds',
    name: "Westgate / Five Corners",
    parentSlug: 'edmonds',
    parentName: "Edmonds",
    route: '/westgate-five-corners-edmonds-in-edmonds-wa',
    bestFit: "Buyers who want Edmonds with practical neighborhood services.",
    tradeoff: "It does not carry the same charm or marine identity as the Bowl.",
    localTexture: "Westgate and Five Corners are where Edmonds starts to feel like an everyday city instead of a waterfront destination.",
    compareNext: "Downtown Edmonds for a stronger sense of place, or Lynnwood for a more corridor-driven version of convenience.",
    medianPrice: 986500,
    homesSold: 52,
    medianDom: 7.0,
    monthsSupply: 2.3,
    newListings: 102,
  },
  {
    slug: 'yost-maplewood-edmonds',
    name: "Yost / Maplewood",
    parentSlug: 'edmonds',
    parentName: "Edmonds",
    route: '/yost-maplewood-edmonds-in-edmonds-wa',
    bestFit: "Buyers who want Edmonds with park access and a more lived-in daily rhythm.",
    tradeoff: "It has less of the waterfront magic that makes Edmonds famous.",
    localTexture: "This is often the part of Edmonds that keeps the city on the table for buyers who like its name but not always its downtown pricing.",
    compareNext: "Meadowdale for more shoreline nature, or Westgate / Five Corners for a more convenience-centered setup.",
    medianPrice: 986500,
    homesSold: 52,
    medianDom: 7.0,
    monthsSupply: 2.3,
    newListings: 102,
  },
  {
    slug: 'chain-lake',
    name: "Chain Lake",
    parentSlug: 'monroe',
    parentName: "Monroe",
    route: '/chain-lake-in-monroe-wa',
    bestFit: "Buyers who want to pressure-test Chain Lake against the other best-known parts of Monroe instead of stopping at the city-wide guide.",
    tradeoff: "This page is a neighborhood-level starting point, so pair Chain Lake with the full Monroe guide and the Snohomish County report before making a block-by-block decision.",
    localTexture: "Monroe is currently around $712K, 15 days on market, and 49 active listings, so Chain Lake should be read inside that broader city market.",
    compareNext: "Compare Chain Lake with Monroe North and Wagner to see which side of Monroe fits better.",
    medianPrice: 712500,
    homesSold: 18,
    medianDom: 15.0,
    monthsSupply: 2.7,
    newListings: 37,
  },
  {
    slug: 'monroe-north',
    name: "Monroe North",
    parentSlug: 'monroe',
    parentName: "Monroe",
    route: '/monroe-north-in-monroe-wa',
    bestFit: "Buyers who want to pressure-test Monroe North against the other best-known parts of Monroe instead of stopping at the city-wide guide.",
    tradeoff: "This page is a neighborhood-level starting point, so pair Monroe North with the full Monroe guide and the Snohomish County report before making a block-by-block decision.",
    localTexture: "Monroe is currently around $712K, 15 days on market, and 49 active listings, so Monroe North should be read inside that broader city market.",
    compareNext: "Compare Monroe North with Wagner and Roosevelt to see which side of Monroe fits better.",
    medianPrice: 712500,
    homesSold: 18,
    medianDom: 15.0,
    monthsSupply: 2.7,
    newListings: 37,
  },
  {
    slug: 'roosevelt',
    name: "Roosevelt",
    parentSlug: 'monroe',
    parentName: "Monroe",
    route: '/roosevelt-in-monroe-wa',
    bestFit: "Buyers who want to pressure-test Roosevelt against the other best-known parts of Monroe instead of stopping at the city-wide guide.",
    tradeoff: "This page is a neighborhood-level starting point, so pair Roosevelt with the full Monroe guide and the Snohomish County report before making a block-by-block decision.",
    localTexture: "Monroe is currently around $712K, 15 days on market, and 49 active listings, so Roosevelt should be read inside that broader city market.",
    compareNext: "Compare Roosevelt with Monroe North and Wagner to see which side of Monroe fits better.",
    medianPrice: 712500,
    homesSold: 18,
    medianDom: 15.0,
    monthsSupply: 2.7,
    newListings: 37,
  },
  {
    slug: 'wagner',
    name: "Wagner",
    parentSlug: 'monroe',
    parentName: "Monroe",
    route: '/wagner-in-monroe-wa',
    bestFit: "Buyers who want to pressure-test Wagner against the other best-known parts of Monroe instead of stopping at the city-wide guide.",
    tradeoff: "This page is a neighborhood-level starting point, so pair Wagner with the full Monroe guide and the Snohomish County report before making a block-by-block decision.",
    localTexture: "Monroe is currently around $712K, 15 days on market, and 49 active listings, so Wagner should be read inside that broader city market.",
    compareNext: "Compare Wagner with Monroe North and Roosevelt to see which side of Monroe fits better.",
    medianPrice: 712500,
    homesSold: 18,
    medianDom: 15.0,
    monthsSupply: 2.7,
    newListings: 37,
  },
  {
    slug: 'hyland',
    name: "Hyland",
    parentSlug: 'granite-falls',
    parentName: "Granite Falls",
    route: '/hyland-in-granite-falls-wa',
    bestFit: "Buyers who want to pressure-test Hyland against the other best-known parts of Granite Falls instead of stopping at the city-wide guide.",
    tradeoff: "This page is a neighborhood-level starting point, so pair Hyland with the full Granite Falls guide and the Snohomish County report before making a block-by-block decision.",
    localTexture: "Granite Falls is currently around $575K, 27 days on market, and 10 active listings, so Hyland should be read inside that broader city market.",
    compareNext: "Compare Hyland with Riverside and Sobey to see which side of Granite Falls fits better.",
    medianPrice: 575000,
    homesSold: 3,
    medianDom: 27.0,
    monthsSupply: 3.3,
    newListings: 6,
  },
  {
    slug: 'pilchuck',
    name: "Pilchuck",
    parentSlug: 'granite-falls',
    parentName: "Granite Falls",
    route: '/pilchuck-in-granite-falls-wa',
    bestFit: "Buyers who want to pressure-test Pilchuck against the other best-known parts of Granite Falls instead of stopping at the city-wide guide.",
    tradeoff: "This page is a neighborhood-level starting point, so pair Pilchuck with the full Granite Falls guide and the Snohomish County report before making a block-by-block decision.",
    localTexture: "Granite Falls is currently around $575K, 27 days on market, and 10 active listings, so Pilchuck should be read inside that broader city market.",
    compareNext: "Compare Pilchuck with Riverside and Sobey to see which side of Granite Falls fits better.",
    medianPrice: 575000,
    homesSold: 3,
    medianDom: 27.0,
    monthsSupply: 3.3,
    newListings: 6,
  },
  {
    slug: 'riverside',
    name: "Riverside",
    parentSlug: 'granite-falls',
    parentName: "Granite Falls",
    route: '/riverside-in-granite-falls-wa',
    bestFit: "Buyers who want to pressure-test Riverside against the other best-known parts of Granite Falls instead of stopping at the city-wide guide.",
    tradeoff: "This page is a neighborhood-level starting point, so pair Riverside with the full Granite Falls guide and the Snohomish County report before making a block-by-block decision.",
    localTexture: "Granite Falls is currently around $575K, 27 days on market, and 10 active listings, so Riverside should be read inside that broader city market.",
    compareNext: "Compare Riverside with Sobey and Hyland to see which side of Granite Falls fits better.",
    medianPrice: 575000,
    homesSold: 3,
    medianDom: 27.0,
    monthsSupply: 3.3,
    newListings: 6,
  },
  {
    slug: 'sobey',
    name: "Sobey",
    parentSlug: 'granite-falls',
    parentName: "Granite Falls",
    route: '/sobey-in-granite-falls-wa',
    bestFit: "Buyers who want to pressure-test Sobey against the other best-known parts of Granite Falls instead of stopping at the city-wide guide.",
    tradeoff: "This page is a neighborhood-level starting point, so pair Sobey with the full Granite Falls guide and the Snohomish County report before making a block-by-block decision.",
    localTexture: "Granite Falls is currently around $575K, 27 days on market, and 10 active listings, so Sobey should be read inside that broader city market.",
    compareNext: "Compare Sobey with Riverside and Hyland to see which side of Granite Falls fits better.",
    medianPrice: 575000,
    homesSold: 3,
    medianDom: 27.0,
    monthsSupply: 3.3,
    newListings: 6,
  },
];

export function getNeighborhoodBySlug(slug: string): SnohoNeighborhood | undefined {
  return snohoNeighborhoods.find(n => n.slug === slug);
}

export function getNeighborhoodsByParent(parentSlug: string): SnohoNeighborhood[] {
  return snohoNeighborhoods.filter(n => n.parentSlug === parentSlug);
}

export function getActiveNeighborhoods(limit = 6): SnohoNeighborhood[] {
  return [...snohoNeighborhoods]
    .sort((a, b) => b.homesSold - a.homesSold)
    .slice(0, limit);
}

export function getNeighborhoodMarketTemp(n: SnohoNeighborhood): "hot" | "balanced" | "cool" {
  if (n.monthsSupply < 2) return "hot";
  if (n.monthsSupply > 3) return "cool";
  return "balanced";
}
